<?php

return [
    /*
     * This is the class responsible for providing the URLs which must be redirected.
     * The only requirement for the redirector is that it needs to implement the
     * `Spatie\MissingPageRedirector\Redirector\Redirector`-interface
     */
    'redirector'            => \Spatie\MissingPageRedirector\Redirector\ConfigurationRedirector::class,

    /*
     * By default the package will only redirect 404s. If you want to redirect on other
     * response codes, just add them to the array. Leave the array empty to redirect
     * always no matter what the response code.
     */
    'redirect_status_codes' => [
        \Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND,
    ],

    /*
     * When using the `ConfigurationRedirector` you can specify the redirects in this array.
     * You can use Laravel's route parameters here.
     */
    'redirects'             => [
        '/author/alec-admin'                                         => '/',
        '/author/alech'                                              => '/',
        '/cart'                                                      => '/',
        '/category/courses'                                          => '/upcoming-courses/solas-safe-pass',
        '/checkout'                                                  => '/',
        '/confined-spaces-safety-awareness'                          => '/find/confined-spaces-courses-dublin',
        '/contact-us'                                                => '/enquiry',
        '/courses/insulation-installation'                           => '/find/mewp-courses-dublin',
        '/courses'                                                   => '/',
        '/events'                                                    => '/',
        '/events/abrasive-wheels'                                    => '/find/abrasive-wheels-courses-dublin',
        '/events/categories/cit'                                     => '/',
        '/events/categories/confined-space'                          => '/find/confined-spaces-courses-dublin',
        '/events/categories/construction'                            => '/',
        '/events/categories/health-safety'                           => '/',
        '/events/categories/health-safety/?pno=2'                    => '/',
        '/events/categories/qqi'                                     => '/',
        '/events/categories/solas'                                   => '/find/solas-safe-pass-courses-dublin',
        '/events/categories/solas/?pno=4'                            => '/find/solas-safe-pass-courses-dublin',
        '/events/chemical-awareness'                                 => '/find/confined-spaces-courses-dublin',
        '/events/confined-spaces-high-risk'                          => '/find/confined-spaces-courses-dublin',
        '/events/confined-spaces-low-risk'                           => '/find/confined-spaces-courses-dublin',
        '/events/confined-spaces-management'                         => '/find/confined-spaces-courses-dublin',
        '/events/confined-spaces-medium-risk'                        => '/find/confined-spaces-courses-dublin',
        '/events/confined-spaces-search-rescue'                      => '/find/confined-spaces-courses-dublin',
        '/events/cscs-180-degree-excavator'                          => '/find/plant-and-machinery-courses-dublin',
        '/events/cscs-360-degree-excavator'                          => '/find/plant-and-machinery-courses-dublin',
        '/events/cscs-mobile-access-tower-scaffold'                  => '/find/plant-and-machinery-courses-dublin',
        '/events/cscs-site-dumper'                                   => '/find/plant-and-machinery-courses-dublin',
        '/events/cscs-slinger-signaller'                             => '/find/plant-and-machinery-courses-dublin',
        '/events/cscs-teleporter'                                    => '/find/plant-and-machinery-courses-dublin',
        '/events/emergency-first-aid'                                => '/find/first-aid-courses-dublin',
        '/events/fire-safety-fire-warden'                            => '/find/fire-safety-courses-dublin',
        '/events/firewarden'                                         => '/find/fire-safety-courses-dublin',
        '/events/forklift'                                           => '/find/plant-and-machinery-courses-dublin',
        '/events/health-and-safety-at-roadworks'                     => '/find/plant-and-machinery-courses-dublin',
        '/events/insulation-installation'                            => '/find/mewp-courses-dublin',
        '/events/iosh-managing-safely-for-construction-managers'     => '/find/management-courses-courses-dublin',
        '/events/iosh-managing-the-role-of-pscs'                     => '/find/management-courses-courses-dublin',
        '/events/iosh-managing-the-role-of-psdp-safety-in-design-2'  => '/find/management-courses-courses-dublin',
        '/events/ladder-safety'                                      => '/find/working-at-heights-courses-dublin',
        '/events/location-of-underground-services'                   => '/find/plant-and-machinery-courses-dublin',
        '/events/locations'                                          => '/',
        '/events/lock-out-tag-out'                                   => '/',
        '/events/manual-handling-2018-08-28'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2018-10-09'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2018-10-23'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2018-11-20'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2019-01-22'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2019-02-05'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2019-03-12'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2019-04-23'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2019-08-13'                         => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2017-11-23'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-01-25'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-02-08'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-07-26'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-08-02'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-09-13'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-09-27'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-10-11'                       => '/find/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-10-18'                       => '/find/manual-handling-courses-dublin',
        '/events/mewp-new'                                           => '/find/mewp-courses-dublin',
        '/events/my-bookings'                                        => '/',
        '/events/occupational-first-aid'                             => '/find/first-aid-courses-dublin',
        '/events/patient-handling-instructor'                        => '/',
        '/events/patientpeople-handling'                             => '/',
        '/events/power-pallet-truck'                                 => '/find/plant-and-machinery-courses-dublin',
        '/events/ride-on-roller'                                     => '/find/plant-and-machinery-courses-dublin',
        '/events/safe-pass-2019-04-25'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-04-26'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-04-27'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-03'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-04'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-11'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-15'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-18'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-25'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-28'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-06-26'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-07'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-08'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-09'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-28'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-31'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-03'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-07'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-19'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-21'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-27'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-03'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-11'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-16'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-29'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-11-08'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-11-29'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-12-03'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-12-11'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-12-19'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-01-08'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-01-11'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-04-15'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-04-17'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-04-24'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-05-05'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-08-26'                               => '/find/solas-safe-pass-courses-dublin',
        '/events/safe-use-of-harnesses'                              => '/find/working-at-heights-courses-dublin',
        '/events/signing-lighting-and-guarding-at-roadworks'         => '/find/plant-and-machinery-courses-dublin',
        '/events/solas-safe-pass-old'                                => '/find/solas-safe-pass-courses-dublin',
        '/events/spill-kit'                                          => '/find/plant-and-machinery-courses-dublin',
        '/events/tags/wood-cutting'                                  => '/',
        '/events/temporary-works'                                    => '/',
        '/events/training-delivery-and-evaluation-train-the-trainer' => '/',
        '/events/vehicle-banksman'                                   => '/find/plant-and-machinery-courses-dublin',
        '/events/wewp'                                               => '/find/mewp-courses-dublin',
        '/events/working-at-heights'                                 => '/find/working-at-heights-courses-dublin',
        '/fetac'                                                     => '/',
        '/home'                                                      => '/',
        '/insulation-installation'                                   => '/find/working-at-heights-courses-dublin',
        'index.php'                                                  => '/',
        '/locations/cit-ltd'                                         => '/',
        '/locations/cit-training-room-10'                            => '/',
        '/locations/cit-training-room-11'                            => '/',
        '/locations/cit-training-room-12'                            => '/',
        '/locations/cit-training-room-13'                            => '/',
        '/locations/cit-training-room-2'                             => '/',
        '/locations/cit-training-room-3'                             => '/',
        '/locations/cit-training-room-4'                             => '/',
        '/locations/designer-group-2'                                => '/',
        '/locations/dunboyn'                                         => '/',
        '/locations/dunboyne-castle-hotel'                           => '/',
        '/locations/grasshopper-inn'                                 => '/venue/the-grasshopper-inn-main-street-clonee-meath',
        '/locations/grasshopper-inn-2'                               => '/venue/the-grasshopper-inn-main-street-clonee-meath',
        '/locations/parslickstown-house'                             => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/parslickstown-house-2'                           => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/parslickstown-house-4'                           => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/parslickstown-house-5'                           => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/the-grasshopper-inn'                             => '/venue/the-grasshopper-inn-main-street-clonee-meath',
        '/locations/training-room'                                   => '/',
        '/locations/master-hospitality-training/'                    => '/',
        '/manual-handling-instructor'                                => '/find/manual-handling-courses-dublin',
        '/my-account'                                                => '/',
        '/shop'                                                      => '/',
        '/solas-safe-pass'                                           => '/find/solas-safe-pass-courses-dublin',
        '/store'                                                     => '/',
        '/testimonial/debbie-mcmahon-ktl'                            => '/enquiry',
        '/testimonial/mairead-twomey-sierra-communications'          => '/enquiry',
        '/testimonial/marie-manders-arup'                            => '/enquiry',
        '/testimonial/michael-ryan-roadbridge-ltd'                   => '/enquiry',
        '/testimonials-archive'                                      => '/enquiry',
        '/upcoming-courses'                                          => '/find/solas-safe-pass-courses-dublin',
    ],

];
