<?php

return [
    /*
     * This is the class responsible for providing the URLs which must be redirected.
     * The only requirement for the redirector is that it needs to implement the
     * `Spatie\MissingPageRedirector\Redirector\Redirector`-interface
     */
    'redirector' => \Spatie\MissingPageRedirector\Redirector\ConfigurationRedirector::class,

    /*
     * By default the package will only redirect 404s. If you want to redirect on other
     * response codes, just add them to the array. Leave the array empty to redirect
     * always no matter what the response code.
     */
    'redirect_status_codes' => [
        \Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND,
    ],

    /*
     * When using the `ConfigurationRedirector` you can specify the redirects in this array.
     * You can use Laravel's route parameters here.
     */
    'redirects' => [
        '/author/alec-admin' => '/',
        '/author/alech' => '/',
        '/cart' => '/',
        '/category/courses' => '/upcoming-courses/solas-safe-pass',
        '/checkout' => '/',
        '/confined-spaces-safety-awareness' => '/courses/confined-spaces-courses-dublin',
        '/contact-us' => '/enquiry',
        '/courses/insulation-installation' => '/courses/mewp-courses-dublin',
        '/courses' => '/',
        '/events' => '/',
        '/events/abrasive-wheels' => '/courses/abrasive-wheels-courses-dublin',
        '/events/categories/cit' => '/',
        '/events/categories/confined-space' => '/courses/confined-spaces-courses-dublin',
        '/events/categories/construction' => '/',
        '/events/categories/health-safety' => '/',
        '/events/categories/health-safety/?pno=2' => '/',
        '/events/categories/qqi' => '/',
        '/events/categories/solas' => '/courses/solas-safe-pass-courses-dublin',
        '/events/categories/solas/?pno=4' => '/courses/solas-safe-pass-courses-dublin',
        '/events/chemical-awareness' => '/courses/confined-spaces-courses-dublin',
        '/events/confined-spaces-high-risk' => '/courses/confined-spaces-courses-dublin',
        '/events/confined-spaces-low-risk' => '/courses/confined-spaces-courses-dublin',
        '/events/confined-spaces-management' => '/courses/confined-spaces-courses-dublin',
        '/events/confined-spaces-medium-risk' => '/courses/confined-spaces-courses-dublin',
        '/events/confined-spaces-search-rescue' => '/courses/confined-spaces-courses-dublin',
        '/events/cscs-180-degree-excavator' => '/courses/plant-and-machinery-courses-dublin',
        '/events/cscs-360-degree-excavator' => '/courses/plant-and-machinery-courses-dublin',
        '/events/cscs-mobile-access-tower-scaffold' => '/courses/plant-and-machinery-courses-dublin',
        '/events/cscs-site-dumper' => '/courses/plant-and-machinery-courses-dublin',
        '/events/cscs-slinger-signaller' => '/courses/plant-and-machinery-courses-dublin',
        '/events/cscs-teleporter' => '/courses/plant-and-machinery-courses-dublin',
        '/events/emergency-first-aid' => '/courses/first-aid-courses-dublin',
        '/events/fire-safety-fire-warden' => '/courses/fire-safety-courses-dublin',
        '/events/firewarden' => '/courses/fire-safety-courses-dublin',
        '/events/forklift' => '/courses/plant-and-machinery-courses-dublin',
        '/events/health-and-safety-at-roadworks' => '/courses/plant-and-machinery-courses-dublin',
        '/events/insulation-installation' => '/courses/mewp-courses-dublin',
        '/events/iosh-managing-safely-for-construction-managers' => '/courses/management-courses-courses-dublin',
        '/events/iosh-managing-the-role-of-pscs' => '/courses/management-courses-courses-dublin',
        '/events/iosh-managing-the-role-of-psdp-safety-in-design-2' => '/courses/management-courses-courses-dublin',
        '/events/ladder-safety' => '/courses/working-at-heights-courses-dublin',
        '/events/location-of-underground-services' => '/courses/plant-and-machinery-courses-dublin',
        '/events/locations' => '/',
        '/events/lock-out-tag-out' => '/',
        '/events/manual-handling-2018-08-28' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2018-10-09' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2018-10-23' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2018-11-20' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2019-01-22' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2019-02-05' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2019-03-12' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2019-04-23' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2019-08-13' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2017-11-23' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-01-25' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-02-08' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-07-26' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-08-02' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-09-13' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-09-27' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-10-11' => '/courses/manual-handling-courses-dublin',
        '/events/manual-handling-2-2018-10-18' => '/courses/manual-handling-courses-dublin',
        '/events/mewp-new' => '/courses/mewp-courses-dublin',
        '/events/my-bookings' => '/',
        '/events/occupational-first-aid' => '/courses/first-aid-courses-dublin',
        '/events/patient-handling-instructor' => '/',
        '/events/patientpeople-handling' => '/',
        '/events/power-pallet-truck' => '/courses/plant-and-machinery-courses-dublin',
        '/events/ride-on-roller' => '/courses/plant-and-machinery-courses-dublin',
        '/events/safe-pass-2019-04-25' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-04-26' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-04-27' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-03' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-04' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-11' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-15' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-18' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-25' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-05-28' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-06-26' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-07' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-08' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-09' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-28' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-08-31' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-03' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-07' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-19' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-21' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-09-27' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-03' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-11' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-16' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-10-29' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-11-08' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-11-29' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-12-03' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-12-11' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2019-12-19' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-01-08' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-01-11' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-04-15' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-04-17' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-04-24' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-05-05' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-pass-2020-08-26' => '/courses/solas-safe-pass-courses-dublin',
        '/events/safe-use-of-harnesses' => '/courses/working-at-heights-courses-dublin',
        '/events/signing-lighting-and-guarding-at-roadworks' => '/courses/plant-and-machinery-courses-dublin',
        '/events/solas-safe-pass-old' => '/courses/solas-safe-pass-courses-dublin',
        '/events/spill-kit' => '/courses/plant-and-machinery-courses-dublin',
        '/events/tags/wood-cutting' => '/',
        '/events/temporary-works' => '/',
        '/events/training-delivery-and-evaluation-train-the-trainer' => '/',
        '/events/vehicle-banksman' => '/courses/plant-and-machinery-courses-dublin',
        '/events/wewp' => '/courses/mewp-courses-dublin',
        '/events/working-at-heights' => '/courses/working-at-heights-courses-dublin',
        '/fetac' => '/',
        '/home' => '/',
        '/insulation-installation' => '/courses/working-at-heights-courses-dublin',
        'index.php' => '/',
        '/locations/cit-ltd' => '/',
        '/locations/cit-training-room-10' => '/',
        '/locations/cit-training-room-11' => '/',
        '/locations/cit-training-room-12' => '/',
        '/locations/cit-training-room-13' => '/',
        '/locations/cit-training-room-2' => '/',
        '/locations/cit-training-room-3' => '/',
        '/locations/cit-training-room-4' => '/',
        '/locations/designer-group-2' => '/',
        '/locations/dunboyn' => '/',
        '/locations/dunboyne-castle-hotel' => '/',
        '/locations/grasshopper-inn' => '/venue/the-grasshopper-inn-main-street-clonee-meath',
        '/locations/grasshopper-inn-2' => '/venue/the-grasshopper-inn-main-street-clonee-meath',
        '/locations/parslickstown-house' => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/parslickstown-house-2' => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/parslickstown-house-4' => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/parslickstown-house-5' => '/venue/parslickstown-house-base-enterprise-centre-ladyswell-road-mulhuddart-dublin-15-dublin-d15-x2vw',
        '/locations/the-grasshopper-inn' => '/venue/the-grasshopper-inn-main-street-clonee-meath',
        '/locations/training-room' => '/',
        '/locations/master-hospitality-training/' => '/',
        '/manual-handling-instructor' => '/courses/manual-handling-courses-dublin',
        '/my-account' => '/',
        '/shop' => '/',
        '/solas-safe-pass' => '/courses/solas-safe-pass-courses-dublin',
        '/store' => '/',
        '/testimonial/debbie-mcmahon-ktl' => '/enquiry',
        '/testimonial/mairead-twomey-sierra-communications' => '/enquiry',
        '/testimonial/marie-manders-arup' => '/enquiry',
        '/testimonial/michael-ryan-roadbridge-ltd' => '/enquiry',
        '/testimonials-archive' => '/enquiry',
        '/upcoming-courses' => '/courses/solas-safe-pass-courses-dublin',
        '/find/solas-safe-pass-courses-dublin' => '/courses/solas-safe-pass-courses-dublin',
        '/find/manual-handling-courses-dublin' => '/courses/manual-handling-courses-dublin',
        '/find/management-courses-courses-dublin' => '/courses/management-courses-dublin',
        '/find/first-aid-courses-dublin' => '/courses/first-aid-courses-dublin',
        '/find/plant-and-machinery-courses-dublin' => '/courses/plant-and-machinery-courses-forklift-dublin',
        '/find/fire-safety-courses-dublin' => '/courses/fire-safety-courses-dublin',
        '/find/working-at-heights-courses-dublin' => '/courses/working-at-heights-courses-dublin',
        '/find/abrasive-wheels-courses-dublin' => '/courses/abrasive-wheels-courses-dublin',
        '/find/confined-spaces-courses-dublin' => '/courses/confined-spaces-courses-dublin',
        '/find/mewp-courses-dublin' => '/courses/mewp-courses-dublin',
        '/find/wellness-vdu-dse-assessment-courses-dublin' => '/courses/wellness-vdu-dse-assessment-courses-dublin',
        '/find/other-courses' => '/courses/other-courses',
        '/blog/how-much-is-safe-pass-in-ireland' => '/faq/how-much-is-safe-pass-in-ireland',
        '/blog/can-you-do-safe-pass-course-online' => '/faq/can-you-do-safe-pass-course-online',
        '/blog/where-can-you-get-safe-pass' => '/faq/where-can-you-get-safe-pass',
        '/blog/what-is-solas-safe-pass' => '/faq/what-is-solas-safe-pass',
    ],

];
